# Generated by Django 4.2.27 on 2026-03-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers_manager', '0181_analyzer_config_phishing_engine_param'),
        ('analyzers_manager', '0185_add_update_schedule_stratosphere_firehol'),
    ]

    operations = [
    ]
