# Generated by Django 4.2.27 on 2026-04-10

from django.db import migrations


def migrate(apps, schema_editor):
    PythonModule = apps.get_model("api_app", "PythonModule")
    pm = PythonModule.objects.filter(
        module="greynoise_labs.GreynoiseLabs",
        base_path="api_app.analyzers_manager.observable_analyzers",
    ).first()
    if pm:
        pm.analyzerconfigs.all().delete()
        pm.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0062_alter_parameter_python_module"),
        ("analyzers_manager", "0189_update_capa_timeout"),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
